binlog:
  datasource:
    warnLog: true
    open: true
    classPath: classpath*:com/example/listener/*.class
    data-source-configs:
      - url: jdbc:mysql://150.158.168.29:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        password: Alice
        userName: root
        serverId: 1
        tableFilters:
          - t_test

